# Generated by Django 5.0.2 on 2024-04-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='user.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='user.user'),
        ),
    ]
